public enum Getallen
{
    een =1,
    twee =2,
    drie=3,
    vier =4,
    vijf=5,
    zes=6,
    zeven=7,
    acht=8,
    negen = 9,
    tien = 10,
    elf = 11,
    twaalf = 12,
    dertien = 13,
    veertien = 14,
    twintig =20,
    dertig = 30,
    veertig = 40,  
    tachtig = 80,
    honderd = 100,
}